name: build-debian-unstable
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zapashcanon/gitea-ocaml-ci:latest
      options: --user root
    steps:
      - uses: actions/checkout@v4

      - name: Cache opam switch
        uses: actions/cache@v4
        with:
          path: _opam
          key: ${{ runner.os }}-opam-${{ hashFiles('dune-project', 'ono.opam', 'vendor/owi/dune-project', 'vendor/owi/owi.opam') }}
          restore-keys: |
            ${{ runner.os }}-opam-

      - name: test
        run: |
          set -x

          export HOME=/root
          
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          # Prepare OCaml stuff
          export OPAMCONFIRMLEVEL=unsafe-yes
          export OPAMYES=1
          opam update

          if [ ! -d "_opam" ]; then
            opam switch create . --deps-only
          fi
          eval "$(opam env --switch=. --set-switch)"

          apt update

          # Install system and opam-repo dependencies
          opam install . --with-test --with-dev-setup --with-doc --deps-only

          # Build and test
          dune build @install
          dune runtest
